name: combien
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.4.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
