name: combien
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.4.0
  freezed: ^2.3.2
  hooks_riverpod: ^2.2.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.2.0

  isar_generator: ^3.0.5
  objectbox_generator: ^1.7.2

flutter:
  uses-material-design: true
